In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int32')

In [7]:
a.ndim

1

In [8]:
a.size

3

In [9]:
a.shape

(3,)

In [10]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])

In [11]:
b.dtype

dtype('float64')

In [12]:
b.ndim

2

In [13]:
b.size

4

In [14]:
b.shape

(2, 2)

In [15]:
b.itemsize

8

In [16]:
b.data

# Create an array

In [18]:
c = np.array([[1, 2, 3],[4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
d = np.array(((1, 2, 3),(4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
g = np.array([['a', 'b'],['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [23]:
g.dtype

dtype('<U1')

In [24]:
g.dtype.name

'str32'

In [25]:
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [26]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [36]:
np.arange(0, 12, 3)

array([0, 3, 6, 9])

In [31]:
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [32]:
np.arange(0, 12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.random.random(3)

array([0.4760569 , 0.16005418, 0.50446781])

In [35]:
np.random.random((3,3))

array([[0.76276018, 0.24334428, 0.43137642],
       [0.90674614, 0.40642959, 0.8972056 ],
       [0.0214298 , 0.79759796, 0.14451007]])

# Basic operation

In [37]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [38]:
a+4

array([4, 5, 6, 7])

In [39]:
a*2

array([0, 2, 4, 6])

In [40]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [41]:
a + b

array([ 4,  6,  8, 10])

In [43]:
a - b

array([-4, -4, -4, -4])

In [44]:
a * b

array([ 0,  5, 12, 21])

In [45]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [46]:
a * np.sqrt(b)

array([0.        , 2.23606798, 4.89897949, 7.93725393])

In [48]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [51]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [52]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [53]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [55]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [56]:
a += 1
a

array([1, 2, 3, 4])

In [58]:
a -= 1
a

array([0, 1, 2, 3])

In [59]:
a += 4
a

array([4, 5, 6, 7])

In [60]:
a *= 2
a

array([ 8, 10, 12, 14])

In [61]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [62]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [63]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [64]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [65]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [66]:
a.sum()

15.0

In [67]:
a.min()

0.3

In [68]:
a.max()

5.7

In [69]:
a.mean()

3.0

In [70]:
a.std()

2.0079840636817816

# Indexing, Slicing, and Iterating 

In [71]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [72]:
a[4]

14

In [74]:
a[-1]

15

In [75]:
a[-6]

10

In [76]:
a[[1, 3, 4]]

array([11, 13, 14])

In [78]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [79]:
A[1, 2]

15

In [80]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [81]:
a[1:5]

array([11, 12, 13, 14])

In [82]:
a[1:5:2]

array([11, 13])

In [83]:
a[::2]

array([10, 12, 14])

In [84]:
a[:5:2]

array([10, 12, 14])

In [85]:
a[:5:]

array([10, 11, 12, 13, 14])

In [86]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [87]:
A[0,:]

array([10, 11, 12])

In [88]:
A[:,0]

array([10, 13, 16])

In [89]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [90]:
A[[0,2], 0:2]

array([[10, 11],
       [16, 17]])

In [91]:
for i in a:
   print(i)


10
11
12
13
14
15


In [92]:
for row in A:
   print( row)



[10 11 12]
[13 14 15]
[16 17 18]


In [93]:
for item in A.flat:
  print( item)


10
11
12
13
14
15
16
17
18


In [94]:
np.apply_along_axis(np.mean, axis=0, arr=A)

array([13., 14., 15.])

In [95]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

In [97]:
def foo(x):
    return x/2
np.apply_along_axis(foo, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

In [98]:
np.apply_along_axis(foo, axis=0, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

# Conditions and Boolean Arrays

In [99]:
A = np.random.random((4, 4))
A

array([[0.82118493, 0.33037276, 0.40002092, 0.93456854],
       [0.35716949, 0.80929835, 0.07381522, 0.22978808],
       [0.43261558, 0.00235197, 0.78940601, 0.76230359],
       [0.65591365, 0.71157627, 0.22996795, 0.57287539]])

In [100]:
A < 0.5

array([[False,  True,  True, False],
       [ True, False,  True,  True],
       [ True,  True, False, False],
       [False, False,  True, False]])

In [101]:
A[A < 0.5]

array([0.33037276, 0.40002092, 0.35716949, 0.07381522, 0.22978808,
       0.43261558, 0.00235197, 0.22996795])

In [102]:
a = np.random.random(12)
a

array([0.17323826, 0.02978215, 0.70467742, 0.43491715, 0.25318128,
       0.67471162, 0.18859814, 0.75577729, 0.95689487, 0.87684169,
       0.22200551, 0.36771596])

In [103]:
A = a.reshape(3, 4)
A


array([[0.17323826, 0.02978215, 0.70467742, 0.43491715],
       [0.25318128, 0.67471162, 0.18859814, 0.75577729],
       [0.95689487, 0.87684169, 0.22200551, 0.36771596]])

In [104]:
a.shape = (3, 4)
a

array([[0.17323826, 0.02978215, 0.70467742, 0.43491715],
       [0.25318128, 0.67471162, 0.18859814, 0.75577729],
       [0.95689487, 0.87684169, 0.22200551, 0.36771596]])

In [106]:
a = a.ravel()
a

array([0.17323826, 0.02978215, 0.70467742, 0.43491715, 0.25318128,
       0.67471162, 0.18859814, 0.75577729, 0.95689487, 0.87684169,
       0.22200551, 0.36771596])

In [109]:
a.shape = (12)
a

array([0.17323826, 0.02978215, 0.70467742, 0.43491715, 0.25318128,
       0.67471162, 0.18859814, 0.75577729, 0.95689487, 0.87684169,
       0.22200551, 0.36771596])

In [108]:
A.transpose()

array([[0.17323826, 0.25318128, 0.95689487],
       [0.02978215, 0.67471162, 0.87684169],
       [0.70467742, 0.18859814, 0.22200551],
       [0.43491715, 0.75577729, 0.36771596]])

# Array Manipulation

In [110]:
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.vstack((A, B))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [112]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
np.column_stack((a, b, c))


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [113]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
[B,C] = np.hsplit(A, 2)
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [116]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [117]:
[B,C] = np.vsplit(A, 2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [118]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
[A1,A2,A3] = np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [120]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [121]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [123]:
[A1,A2,A3] = np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [124]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
A3

array([[12, 13, 14, 15]])

# General concepts

In [126]:
a = np.array([1, 2, 3, 4])
b = a
b

array([1, 2, 3, 4])

In [127]:
a[2] = 0

In [128]:
b

array([1, 2, 0, 4])

In [130]:
c = a[0:2]
c

array([1, 2])

In [131]:
a[0] = 0
c

array([0, 2])

In [133]:
a = np.array([1, 2, 3, 4])
c = a.copy()
c

array([1, 2, 3, 4])

In [134]:
a[0] = 0
c

array([1, 2, 3, 4])

# Vectorization

In [135]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
b

array([0, 1, 2, 3])

In [137]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [139]:
m = np.arange(6).reshape(3, 1, 2)
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [140]:
n = np.arange(6).reshape(3, 2, 1)
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [142]:
m + n

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

# Structured Arrays

In [143]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3, 2-2j), (3, 'Third', 0.8, 1+3j)],dtype=('i2, a6, f4, c8'))
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [145]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,2-2j), (3, 'Third', 0.8, 1+3j)],dtype=('int16, a6, float32, complex64'))
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [146]:
structured[1]

(2, b'Second', 1.3, 2.-2.j)

In [147]:
structured['f1']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [148]:
structured = np.array([(1,'First',0.5,1+2j),(2,'Second',1.3,2-2j),(3,'Third',0.8,1+3j)],dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')])
structured


array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [149]:
structured.dtype.names = ('id','order','value','complex')

In [150]:
structured['order']

array([b'First', b'Second', b'Third'], dtype='|S6')

# Reading and Writing Array Data on Files

In [152]:
## NON C'E' QUESTA RIGA - DA AGGIUNGERE!!!!!! ##

data = np.random.random((3,3))
data

array([[0.47941017, 0.43759768, 0.76636206],
       [0.51928993, 0.06358527, 0.72109914],
       [0.64501488, 0.94113659, 0.42052306]])

In [153]:
np.save('saved_data',data)

In [155]:
loaded_data = np.load('saved_data.npy')
loaded_data

array([[0.47941017, 0.43759768, 0.76636206],
       [0.51928993, 0.06358527, 0.72109914],
       [0.64501488, 0.94113659, 0.42052306]])

In [156]:
data = np.genfromtxt('ch3_data.csv', delimiter=',', names=True)
data

array([(1., 123., 1.4, 23.), (2., 110., 0.5, 18.), (3., 164., 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [157]:
data2 = np.genfromtxt('ch3_data2.csv', delimiter=',', names=True)
data2

array([(1., 123., 1.4, 23.), (2., 110., nan, 18.), (3.,  nan, 2.1, 19.)],
      dtype=[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')])

In [158]:
data2['id']

array([1., 2., 3.])

In [159]:
data2[0]

(1., 123., 1.4, 23.)