In [1]:
import numpy as np
import pandas as pd
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [3]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                      'color': ['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [4]:
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [5]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                     'color': ['white','red','red','black','green'],
                     'brand': ['OMG','ABC','ABC','POD','POD']})
frame1


id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [6]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                     'brand': ['OMG','POD','ABC','POD']})
frame2


id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [7]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [8]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [9]:
pd.merge(frame1,frame2,on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [16]:
frame2.columns = ['sid','brand']
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [18]:
pd.merge(frame1, frame2, left_on='id', right_on='sid')

id  color brand_x     sid brand_y
0    ball  white     OMG    ball     ABC
1  pencil    red     ABC  pencil     OMG
2  pencil    red     ABC  pencil     POD
3     pen    red     ABC     pen     POD

In [20]:
frame2.columns = ['id','brand']

In [21]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [22]:
pd.merge(frame1,frame2,on='id',how='outer')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [23]:
pd.merge(frame1,frame2,on='id',how='left')

id  color brand_x brand_y
0     ball  white     OMG     ABC
1   pencil    red     ABC     OMG
2   pencil    red     ABC     POD
3      pen    red     ABC     POD
4      mug  black     POD     NaN
5  ashtray  green     POD     NaN

In [24]:
pd.merge(frame1,frame2,on='id',how='right')

id  color brand_x brand_y
0  pencil    red     ABC     OMG
1  pencil    red     ABC     POD
2    ball  white     OMG     ABC
3     pen    red     ABC     POD

In [25]:
pd.merge(frame1,frame2,on=['id','brand'],how='outer')

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD
5   pencil    NaN   OMG
6   pencil    NaN   POD
7     ball    NaN   ABC
8      pen    NaN   POD

# Merging on an Index

In [26]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id_x  color brand_x    id_y brand_y
0    ball  white     OMG  pencil     OMG
1  pencil    red     ABC  pencil     POD
2     pen    red     ABC    ball     ABC
3     mug  black     POD     pen     POD

In [27]:
frame1.join(frame2)

ValueError: columns overlap but no suffix specified: Index(['id', 'brand'], dtype='object')

In [28]:
frame2.columns = ['id2','brand2']

In [31]:
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

# Concatenating

In [32]:
array1 = np.arange(9).reshape((3,3))
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
array2 = np.arange(9).reshape((3,3))+6
array2


array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
np.concatenate([array1,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [35]:
np.concatenate([array1,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

1    0.006149
2    0.162993
3    0.405546
4    0.619234
dtype: float64

In [38]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.245217
6    0.547083
7    0.880713
8    0.860623
dtype: float64

In [39]:
pd.concat([ser1,ser2])

1    0.006149
2    0.162993
3    0.405546
4    0.619234
5    0.245217
6    0.547083
7    0.880713
8    0.860623
dtype: float64

In [40]:
pd.concat([ser1,ser2],axis=1)

0         1
1  0.006149       NaN
2  0.162993       NaN
3  0.405546       NaN
4  0.619234       NaN
5       NaN  0.245217
6       NaN  0.547083
7       NaN  0.880713
8       NaN  0.860623

In [41]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.006149
   2    0.162993
   3    0.405546
   4    0.619234
2  5    0.245217
   6    0.547083
   7    0.880713
   8    0.860623
dtype: float64

In [42]:
pd.concat([ser1,ser2], axis=1, keys=[1,2])

1         2
1  0.006149       NaN
2  0.162993       NaN
3  0.405546       NaN
4  0.619234       NaN
5       NaN  0.245217
6       NaN  0.547083
7       NaN  0.880713
8       NaN  0.860623

In [43]:
frame1 = pd.DataFrame(np.random.rand(9).reshape(3,3), 
                      index=[1,2,3], 
                      columns=['A','B','C'])
frame2 = pd.DataFrame(np.random.rand(9).reshape(3,3), 
                      index=[4,5,6], 
                      columns=['A','B','C'])

In [44]:
pd.concat([frame1, frame2])

A         B         C
1  0.313227  0.373514  0.662668
2  0.725699  0.113770  0.893991
3  0.258105  0.260403  0.603132
4  0.435601  0.360358  0.988300
5  0.716622  0.021754  0.867438
6  0.515336  0.918546  0.117240

In [45]:
pd.concat([frame1, frame2], axis=1)

A         B         C         A         B         C
1  0.313227  0.373514  0.662668       NaN       NaN       NaN
2  0.725699  0.113770  0.893991       NaN       NaN       NaN
3  0.258105  0.260403  0.603132       NaN       NaN       NaN
4       NaN       NaN       NaN  0.435601  0.360358  0.988300
5       NaN       NaN       NaN  0.716622  0.021754  0.867438
6       NaN       NaN       NaN  0.515336  0.918546  0.117240

# Combining

In [47]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
ser1

1    0.081604
2    0.176874
3    0.022847
4    0.752198
5    0.898431
dtype: float64

In [48]:
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
ser2

2    0.171248
4    0.954797
5    0.637817
6    0.129753
dtype: float64

In [49]:
ser1.combine_first(ser2)

1    0.081604
2    0.176874
3    0.022847
4    0.752198
5    0.898431
6    0.129753
dtype: float64

In [50]:
ser2.combine_first(ser1)

1    0.081604
2    0.171248
3    0.022847
4    0.954797
5    0.637817
6    0.129753
dtype: float64

In [51]:
ser1[:3].combine_first(ser2[:3])

1    0.081604
2    0.176874
3    0.022847
4    0.954797
5    0.637817
dtype: float64

# Pivoting

In [54]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                    index=['white','black','red'],
                    columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [56]:
ser5 = frame1.stack()
ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [57]:
ser5.unstack()


ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [58]:
ser5.unstack(0)

white  black  red
ball        0      3    6
pen         1      4    7
pencil      2      5    8

In [59]:
longframe = pd.DataFrame({ 'color':['white','white','white',
                                  'red','red','red',
                                  'black','black','black'],
                         'item':['ball','pen','mug',
                                 'ball','pen','mug',
                                 'ball','pen','mug'],
                         'value': np.random.rand(9)})
longframe

color  item     value
0  white  ball  0.305909
1  white   pen  0.615253
2  white   mug  0.957373
3    red  ball  0.699478
4    red   pen  0.450290
5    red   mug  0.394437
6  black  ball  0.843243
7  black   pen  0.105823
8  black   mug  0.379546

In [64]:
wideframe = longframe.pivot(index='color',columns='item')
wideframe

value                    
item       ball       mug       pen
color                              
black  0.843243  0.379546  0.105823
red    0.699478  0.394437  0.450290
white  0.305909  0.957373  0.615253

# Removing

In [65]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                    index=['white','black','red'],
                    columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [66]:
del frame1['ball']

In [67]:
frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [68]:
frame1.drop('white')

pen  pencil
black    4       5
red      7       8

# Data Transformation

In [69]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
                      'value': [2,1,3,3,2]})
dframe


color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [70]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [71]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [72]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

# Mapping

In [74]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                       'color':['white','rosso','verde','black','yellow'],
                       'price':[5.56,4.20,1.30,0.56,2.75]})
frame


item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [75]:
newcolors = {
    'rosso': 'red',
    'verde': 'green'
}


In [76]:
frame.replace(newcolors)

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [78]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [79]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

In [80]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
                     'color':['white','red','green','black','yellow']})
frame


item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [81]:
prices = {
    'ball' : 5.56,
    'mug' : 4.20,
    'bottle' : 1.30,
    'scissors' : 3.41,
    'pen' : 1.30,
    'pencil' : 0.56,
    'ashtray' : 2.75
}


In [82]:
frame['price'] = frame['item'].map(prices)

In [83]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

# Rename the Indexes of the Axes

In [84]:
reindex = {
   0: 'first',
   1: 'second',
   2: 'third',
   3: 'fourth',
   4: 'fifth'}


In [85]:
frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [86]:
recolumn = {
    'item':'object',
    'price': 'value'}


In [87]:
frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [88]:
frame.rename(index={1:'first'}, columns={'item':'object'})

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

In [89]:
frame.rename(columns={'item':'object'}, inplace=True)

In [90]:
frame

object   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

# Discretization and Binning

In [91]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]

In [92]:
bins = [0,25,50,75,100]

In [94]:
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [95]:
cat.categories

IntervalIndex([(0, 25], (25, 50], (50, 75], (75, 100]], dtype='interval[int64, right]')

In [96]:
cat.codes

array([0, 1, 2, 2, 1, 3, 3, 0, 0, 2, 2, 1, 3, 0, 1, 3, 3], dtype=int8)

In [97]:
pd.value_counts(cat)

(75, 100]    5
(0, 25]      4
(25, 50]     4
(50, 75]     4
dtype: int64

In [98]:
bin_names = ['unlikely','less likely','likely','highly likely']

In [99]:
pd.cut(results, bins, labels=bin_names)

['unlikely', 'less likely', 'likely', 'likely', 'less likely', ..., 'highly likely', 'unlikely', 'less likely', 'highly likely', 'highly likely']
Length: 17
Categories (4, object): ['unlikely' < 'less likely' < 'likely' < 'highly likely']

In [100]:
pd.cut(results, 5)

[(2.904, 22.2], (22.2, 41.4], (60.6, 79.8], (41.4, 60.6], (22.2, 41.4], ..., (79.8, 99.0], (22.2, 41.4], (41.4, 60.6], (79.8, 99.0], (79.8, 99.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.904, 22.2] < (22.2, 41.4] < (41.4, 60.6] < (60.6, 79.8] < (79.8, 99.0]]

In [102]:
quintiles = pd.qcut(results, 5)
quintiles

[(2.999, 24.0], (24.0, 46.0], (62.6, 87.0], (46.0, 62.6], (24.0, 46.0], ..., (62.6, 87.0], (2.999, 24.0], (46.0, 62.6], (87.0, 99.0], (62.6, 87.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.999, 24.0] < (24.0, 46.0] < (46.0, 62.6] < (62.6, 87.0] < (87.0, 99.0]]

In [103]:
pd.value_counts(quintiles)

(2.999, 24.0]    4
(62.6, 87.0]     4
(24.0, 46.0]     3
(46.0, 62.6]     3
(87.0, 99.0]     3
dtype: int64

# Detecting and Filtering Outliers

In [104]:
randframe = pd.DataFrame(np.random.randn(1000,3))

In [105]:
randframe.describe()

0            1            2
count  1000.000000  1000.000000  1000.000000
mean     -0.000460    -0.017767     0.046315
std       1.042408     0.994566     0.992991
min      -3.212585    -3.061143    -3.001813
25%      -0.685317    -0.729519    -0.657947
50%      -0.013876    -0.015765     0.031649
75%       0.735339     0.639109     0.754737
max       3.736956     3.032272     2.654699

In [106]:
randframe.std()

0    1.042408
1    0.994566
2    0.992991
dtype: float64

In [110]:
randframe[(np.abs(randframe) > (3*randframe.std())).any(axis=1)]

0         1         2
74   1.827168  3.032272  0.273040
173  3.736956 -0.028008 -1.427567
183  1.126056 -3.061143 -1.271162
328  3.178242 -1.025444  1.721102
520 -1.680656 -1.085012 -2.981769
645 -0.693923 -1.013091 -3.001813
930 -3.212585 -1.373667 -0.778113

# Permutation

In [109]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [111]:
new_order = np.random.permutation(5)
new_order

array([1, 2, 0, 3, 4])

In [112]:
nframe.take(new_order)

0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
0   0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24

In [113]:
new_order = [3,4,2]
nframe.take(new_order)

0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24
2  10  11  12  13  14

# Random Sampling

In [114]:
sample = np.random.randint(0, len(nframe), size=3)
sample

array([2, 2, 1])

In [115]:
nframe.take(sample)

0   1   2   3   4
2  10  11  12  13  14
2  10  11  12  13  14
1   5   6   7   8   9

# String Manipulation

In [116]:
text = '16 Bolton Avenue , Boston'

In [117]:
text.split(',')

['16 Bolton Avenue ', ' Boston']

In [118]:
tokens = [s.strip() for s in text.split(',')]
tokens

['16 Bolton Avenue', 'Boston']

In [119]:
address, city = [s.strip() for s in text.split(',')]
address

'16 Bolton Avenue'

In [120]:
city

'Boston'

In [121]:
address + ',' + city

'16 Bolton Avenue,Boston'

In [122]:
strings = ['A+','A','A-','B','BB','BBB','C+']

In [123]:
';'.join(strings)

'A+;A;A-;B;BB;BBB;C+'

In [124]:
'Boston' in text

True

In [125]:
text.index('Boston')

19

In [126]:
text.find('Boston')

19

In [127]:
text.index('New York')

ValueError: substring not found

In [128]:
text.find('New York')

-1

In [129]:
text.count('e')

2

In [130]:
text.count('Avenue')

1

In [131]:
text.replace('Avenue','Street')

'16 Bolton Street , Boston'

In [133]:
text.replace('1', '')

'6 Bolton Avenue , Boston'

# Regular Expressions

In [134]:
import re

In [135]:
text = "This is      an\t odd  \n text!"

In [136]:
re.split('\s+', text)

['This', 'is', 'an', 'odd', 'text!']

In [137]:
regex = re.compile('\s+')

In [138]:
regex.split(text)

['This', 'is', 'an', 'odd', 'text!']

In [139]:
text = 'This is my address: 16 Bolton Avenue, Boston'
re.findall('A\w+',text)


['Avenue']

In [140]:
re.findall('[A,a]\w+',text)

['address', 'Avenue']

In [141]:
re.search('[A,a]\w+',text)

<re.Match object; span=(11, 18), match='address'>

In [142]:
search = re.search('[A,a]\w+',text)
search.start()


11

In [143]:
search.end()

18

In [144]:
text[search.start():search.end()]

'address'

In [145]:
re.match('[A,a]\w+',text)

In [146]:
re.match('T\w+',text)

<re.Match object; span=(0, 4), match='This'>

In [147]:
match = re.match('T\w+',text)

In [148]:
text[match.start():match.end()]

'This'

# Data Aggregation

In [149]:
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],
                     'object': ['pen','pencil','pencil','ashtray','pen'],
                     'price1' : [5.56,4.20,1.30,0.56,2.75],
                     'price2' : [4.75,4.12,1.60,0.75,3.15]})
frame


color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [151]:
group = frame['price1'].groupby(frame['color'])
group

In [152]:
group.groups

{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [153]:
group.mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [154]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

In [155]:
ggroup = frame['price1'].groupby([frame['color'],frame['object']])
ggroup.groups

{('green', 'pen'): [4], ('green', 'pencil'): [2], ('red', 'ashtray'): [3], ('red', 'pencil'): [1], ('white', 'pen'): [0]}

In [156]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [162]:
frame[['price1','price2']].groupby(frame['color']).mean()

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [163]:
frame.groupby(frame['color']).mean(numeric_only=True)

price1  price2
color                
green   2.025   2.375
red     2.380   2.435
white   5.560   4.750

In [164]:
for name, group in frame.groupby('color'):
     print(name)
     print(group)


green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.12
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen    5.56    4.75


# Chain of Transformations

In [166]:
result1 = frame['price1'].groupby(frame['color']).mean()
type(result1)

pandas.core.series.Series

In [170]:
result2 = frame.groupby(frame['color']).mean(numeric_only=True)
type(result2)

pandas.core.frame.DataFrame

In [171]:
frame['price1'].groupby(frame['color']).mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [172]:
frame.groupby(frame['color'])['price1'].mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [174]:
(frame.groupby(frame['color']).mean(numeric_only=True))['price1']

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [178]:
means = frame.groupby('color').mean(numeric_only=True).add_prefix('mean_')
means

mean_price1  mean_price2
color                          
green        2.025        2.375
red          2.380        2.435
white        5.560        4.750

# Functions on Groups

In [179]:
group = frame.groupby('color')
group['price1'].quantile(0.6)

color
green    2.170
red      2.744
white    5.560
Name: price1, dtype: float64

In [180]:
def range(series):
      return series.max() - series.min()
group['price1'].agg(range)


color
green    1.45
red      3.64
white    0.00
Name: price1, dtype: float64

C:\Users\nelli\AppData\Local\Temp\ipykernel_5280\2919840691.py:1: FutureWarning: ['object'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  group.agg(range)


price1  price2
color                
green    1.45    1.55
red      3.64    3.37
white    0.00    0.00

In [192]:
group['price1'].agg(['mean','std',range])

mean       std  range
color                        
green  2.025  1.025305   1.45
red    2.380  2.573869   3.64
white  5.560       NaN   0.00

# Advanced Data Aggregation

In [195]:
frame = pd.DataFrame({ 'color':['white','red','green','red','green'],
                     'price1':[5.56,4.20,1.30,0.56,2.75],
                     'price2':[4.75,4.12,1.60,0.75,3.15]})
frame


color  price1  price2
0  white    5.56    4.75
1    red    4.20    4.12
2  green    1.30    1.60
3    red    0.56    0.75
4  green    2.75    3.15

In [197]:
sums = frame.groupby('color').sum().add_prefix('tot_')
sums

tot_price1  tot_price2
color                        
green        4.05        4.75
red          4.76        4.87
white        5.56        4.75

In [199]:
pd.merge(frame,sums,left_on='color',right_index=True)

color  price1  price2  tot_price1  tot_price2
0  white    5.56    4.75        5.56        4.75
1    red    4.20    4.12        4.76        4.87
3    red    0.56    0.75        4.76        4.87
2  green    1.30    1.60        4.05        4.75
4  green    2.75    3.15        4.05        4.75

In [200]:
frame.groupby('color').transform(np.sum).add_prefix('tot_')

tot_price1  tot_price2
0        5.56        4.75
1        4.76        4.87
2        4.05        4.75
3        4.76        4.87
4        4.05        4.75

In [201]:
frame = pd.DataFrame( { 'color':['white','black','white','white','black','black'],
                      'status':['up','up','down','down','down','up'],
                      'value1':[12.33,14.55,22.34,27.84,23.40,18.33],
                      'value2':[11.23,31.80,29.99,31.18,18.25,22.44]})
frame


color status  value1  value2
0  white     up   12.33   11.23
1  black     up   14.55   31.80
2  white   down   22.34   29.99
3  white   down   27.84   31.18
4  black   down   23.40   18.25
5  black     up   18.33   22.44

In [202]:
 frame.groupby(['color','status']).apply( lambda x: x.max())

color status  value1  value2
color status                              
black down    black   down   23.40   18.25
      up      black     up   18.33   31.80
white down    white   down   27.84   31.18
      up      white     up   12.33   11.23

In [203]:
frame.rename(index=reindex, columns=recolumn)

color status  value1  value2
first   white     up   12.33   11.23
second  black     up   14.55   31.80
third   white   down   22.34   29.99
fourth  white   down   27.84   31.18
fifth   black   down   23.40   18.25
5       black     up   18.33   22.44

In [205]:
temp = pd.date_range('1/1/2015', periods=10, freq= 'H')
temp

DatetimeIndex(['2015-01-01 00:00:00', '2015-01-01 01:00:00',
               '2015-01-01 02:00:00', '2015-01-01 03:00:00',
               '2015-01-01 04:00:00', '2015-01-01 05:00:00',
               '2015-01-01 06:00:00', '2015-01-01 07:00:00',
               '2015-01-01 08:00:00', '2015-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='H')

In [206]:
timeseries = pd.Series(np.random.rand(10), index=temp)
timeseries

2015-01-01 00:00:00    0.632885
2015-01-01 01:00:00    0.794342
2015-01-01 02:00:00    0.012016
2015-01-01 03:00:00    0.020823
2015-01-01 04:00:00    0.126550
2015-01-01 05:00:00    0.286676
2015-01-01 06:00:00    0.472508
2015-01-01 07:00:00    0.009264
2015-01-01 08:00:00    0.642922
2015-01-01 09:00:00    0.428499
Freq: H, dtype: float64

In [207]:
timetable = pd.DataFrame( {'date': temp, 'value1' : np.random.rand(10),
                                       'value2' : np.random.rand(10)})
timetable


date    value1    value2
0 2015-01-01 00:00:00  0.906140  0.280552
1 2015-01-01 01:00:00  0.084979  0.762092
2 2015-01-01 02:00:00  0.119736  0.886329
3 2015-01-01 03:00:00  0.399677  0.471942
4 2015-01-01 04:00:00  0.024102  0.442855
5 2015-01-01 05:00:00  0.162759  0.019977
6 2015-01-01 06:00:00  0.819687  0.217307
7 2015-01-01 07:00:00  0.962448  0.883598
8 2015-01-01 08:00:00  0.070094  0.781566
9 2015-01-01 09:00:00  0.210208  0.239284

In [208]:
timetable['cat'] = ['up','down','left','left','up','up','down','right','right','up']
timetable


date    value1    value2    cat
0 2015-01-01 00:00:00  0.906140  0.280552     up
1 2015-01-01 01:00:00  0.084979  0.762092   down
2 2015-01-01 02:00:00  0.119736  0.886329   left
3 2015-01-01 03:00:00  0.399677  0.471942   left
4 2015-01-01 04:00:00  0.024102  0.442855     up
5 2015-01-01 05:00:00  0.162759  0.019977     up
6 2015-01-01 06:00:00  0.819687  0.217307   down
7 2015-01-01 07:00:00  0.962448  0.883598  right
8 2015-01-01 08:00:00  0.070094  0.781566  right
9 2015-01-01 09:00:00  0.210208  0.239284     up